name: Get organization members
on:
  issues:
    types: [labeled]
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Install node"
        uses: actions/setup-node@v1
      - name: "🐱‍💻 Install NPM dependencies"
        run: npm install
      - name: " Run code"
        run: node index.js
        env:
          PROFILE_STATS_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      - name: "✍️ Update README.md"
        run: |
          git config user.name "openimbot"
          git config user.email "info@openim.io"
          git add .
          git commit -m "📈 Update member"
      - name: "🚀 push"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
